name: '🚀 Lancer CI (Avec Menu)'

on:
  workflow_dispatch:
    inputs:
      app-repo:
        description: 'Dépôt de l application'
        required: true
        default: 'nohaila1231/app-1-auth'
      node-version:
        description: 'Version Node.js'
        type: choice
        options: ['16', '18', '20', '22']
        default: '18'
      run-tests:
        description: 'Exécuter les tests'
        type: boolean
        default: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le dépôt cible
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.app-repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Tests
        if: ${{ inputs.run-tests == true }}
        run: npm test
      
      - name: Build
        run: npm run build
